name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: "The environment I need to deploy on"
        required: true
        default: "prod"

jobs:
  manual_job:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.Environment }} # Utilisez l'input ici
    steps:
      - name: Access MY_APY_URL
        run: |
          echo "Environment variable MY_APY_URL: ${{ vars.MY_APY_URL }}"
      - name: Simulate Deployment
        run: |
          echo "Deploying to environment: ${{ github.event.inputs.Environment }}"
          # Ajoutez ici vos commandes de déploiement
      - name: Mark as Success
        if: ${{ success() }}
        run: echo "Deployment succeeded!"

      - name: Mark as Failure
        if: ${{ failure() }}
        run: echo "Deployment failed."
